#ifndef TASK1_OPERATIONTYPE_H
#define TASK1_OPERATIONTYPE_H

enum class OperationType {
    BINARY_INFIX,
    UNARY_POSTFIX,
    UNARY_FUNCTION,
    BINARY_FUNCTION,
    ABSTRACT
};

#endif //TASK1_OPERATIONTYPE_H
